// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_activate_cooling from "./routes/api/activate-cooling.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $CoolingButton from "./islands/CoolingButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/activate-cooling.ts": $api_activate_cooling,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Chart.tsx": $Chart,
    "./islands/CoolingButton.tsx": $CoolingButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
